# Generated by Django 3.2.7 on 2021-09-16 22:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('sku', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('fab_year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicycletron.brand')),
            ],
        ),
    ]
