# Generated by Django 3.2.7 on 2021-09-16 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycletron', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicycle',
            old_name='brand_id',
            new_name='brand',
        ),
    ]
